freely parameters

diff --git a/chres b/chres
--- a/chres
+++ b/chres
@@ -1,9 +1,12 @@
 #!/bin/bash
 
-loadconf () {
-	base=$(dirname $(realpath $0))
-	source $base/chres.conf
-}
+version=0.1
+
+load () { source $(dirname $(realpath $0))/$1; }
+
+load chres.conf
+load libs
+
 
 get_resols () {
 	declare -A local _arr
@@ -56,6 +59,8 @@ reset () {
 set_resol () {
 	local wxh=$1
 
+	[[ -z $1 ]] || [[ -z $display ]] && echo "Missing argument for set_resol"
+
 	[[ $wxh == "default" ]] && { reset; return; }
 
 	local wh=$(echo $wxh | awk '{print $1,$2}' FS="x")
@@ -67,8 +72,12 @@ set_resol () {
 	xrandr --output $display --mode ${wxh}_$frec.00 2>/dev/null
 }
 
+get_interfaces () {
+	xrandr | grep ' connected' | egrep -o -i ^[a-z][a-z0-9\-]*
+}
+
 get_display () {
-	set -- $(xrandr | grep ' connected' | egrep -o -i ^[a-z][a-z0-9\-]*)
+	set -- $(get_interfaces)
 
 	case $# in 
 		0)
@@ -115,9 +124,79 @@ get_alias () {
 	return 0
 }
 
+options () 
+{
+	local help=$(cat <<-TEXT
 
-# Load settings
-loadconf
+	Usage:
+
+	    $(basename $0) <options>
+
+	Change easly display resolution
+
+	Options:
+
+	 -d, --display                   specify display interface ($(get_interfaces),...)
+	 -r, --resolution                set display resolution
+	 -R. --reset                     set default resolution
+
+	 -h, --help                      display this help
+	 -v, --version                   display version
+
+TEXT
+)
+
+	declare -A opts
+	declare -A op_aliases
+	local alias
+
+	op_aliases=([display]='-d,--display' [resolution]='-r,--resolution' [reset]='-R,--reset') 
+
+	case $1 in 
+		-h|--help)	 
+		echo -e "$help"
+		exit 0
+		;;
+
+		-v|--version)	 
+		echo "$(basename $0) version $version"
+		exit 0
+		;;
+	esac
+
+	while [ $# -gt 0 ]; do
+		for alias in ${!op_aliases[@]}; do
+			explode ${op_aliases[$alias]} ',' op
+
+			in_array $1 op
+			if [[ $? -eq 0 ]]; then
+				[[ ! -z $2 ]] && val=$2 || val=on
+				eval "$alias=$val"
+			fi	
+		done
+
+		[[ -z $val ]] && shift 2 || shift
+	done
+}
+
+
+options $@
+
+
+# Get / select display
+[[ -z $display ]] && get_display
+
+if [[ ! -z $resolution ]]; then
+	echo echo "Changing to $resolution $display $screen"
+	set_resol "$resolution"
+	exit 0
+fi
+
+if [[ ! -z $reset ]]; then
+	echo "Reseting $display $screen"
+	reset
+	exit 0
+fi
 
 # Try with aliases
 if [[ -z $(egrep '[1-3]\.[0-9]+' <<< $ratio) ]]; then
@@ -140,9 +219,6 @@ if [[ -z $(egrep '[0-9]{3,}x[0-9]{3,}' <<< $minres) ]]; then
 fi	
 
 
-# Get / select display
-get_display
-
 # Select automaticaly some resolutions 
 get_resols
 
@@ -157,7 +233,7 @@ do
 		continue
 	fi
 
-	echo "Changing to $res"
+	echo "Changing to $res $display $screen"
 	sleep 1
 	set_resol "$res"
 done
